project:
  type: website
  output-dir: docs

website:
  title: "CSS 211: Statistical Methods for Computational Social Science"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: syllabus.qmd
        text: "Syllabus"
      - href: schedule.qmd
        text: "Schedule"
      - href: final_project.qmd
        text: "Final Project"
      - text: "Lectures"
        menu:
          - href: lectures/week0-intro.qmd
            text: "Week 0: Course Introduction"
          - href: lectures/week1-philosophy.qmd
            text: "Week 1: Philosophy of Science"
          - href: lectures/week1-r-intro.qmd
            text: "Week 1: Introduction to R"
          - href: lectures/week2-wrangling.qmd
            text: "Week 2: Data Wrangling"
          - href: lectures/week3-visualization.qmd
            text: "Week 3: Data Visualization"
      - text: "Labs"
        icon: fas fa-laptop-code
        menu:
          - text: "Lab 1: R Basics"
            href: labs/lab1.html
      - text: "Hands-on exercises"
        menu:
          - text: "Week 2: Wrangling"
            href: hands_on/week2.qmd
      - text: "Resources"
        menu:
          - text: "Readings"
            href: readings.qmd
    right:
      - icon: github
        href: https://github.com/seantrott/ucsd_css211

format:
  html:
    theme: flatly
    css: styles.css
    toc: true