project:
  type: website
  output-dir: docs

website:
  title: "CSS 211: Statistical Methods for Computational Social Science"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: syllabus.qmd
        text: "Syllabus"
      - href: schedule.qmd
        text: "Schedule"
      - href: final_project.qmd
        text: "Final Project"
      - text: "Lectures"
        menu:
          - href: lectures/week0-intro.qmd
            text: "Week 0: Course Introduction"
          - href: lectures/week1-philosophy.qmd
            text: "Week 1: Philosophy of Science"
      - text: "Labs"
        menu:
          - href: labs/lab1-r-basics.qmd
            text: "Lab 1: R Basics"
      - text: "Resources"
        menu:
          - href: resources/r-resources.qmd
            text: "R Resources"
          - href: resources/datasets.qmd
            text: "Datasets"
          - href: resources/readings.qmd
            text: "Readings"
    right:
      - icon: github
        href: https://github.com/seantrott/ucsd_css211

format:
  html:
    theme: flatly
    css: styles.css
    toc: true